// List of all 195 countries with their ISO country codes
export const countries = [
    { country_name: "Afghanistan", country_code: "AF" },
    { country_name: "Albania", country_code: "AL" },
    { country_name: "Algeria", country_code: "DZ" },
    { country_name: "Andorra", country_code: "AD" },
    { country_name: "Angola", country_code: "AO" },
    { country_name: "Antigua and Barbuda", country_code: "AG" },
    { country_name: "Argentina", country_code: "AR" },
    { country_name: "Armenia", country_code: "AM" },
    { country_name: "Australia", country_code: "AU" },
    { country_name: "Austria", country_code: "AT" },
    { country_name: "Azerbaijan", country_code: "AZ" },
    { country_name: "Bahamas", country_code: "BS" },
    { country_name: "Bahrain", country_code: "BH" },
    { country_name: "Bangladesh", country_code: "BD" },
    { country_name: "Barbados", country_code: "BB" },
    { country_name: "Belarus", country_code: "BY" },
    { country_name: "Belgium", country_code: "BE" },
    { country_name: "Belize", country_code: "BZ" },
    { country_name: "Benin", country_code: "BJ" },
    { country_name: "Bhutan", country_code: "BT" },
    { country_name: "Bolivia", country_code: "BO" },
    { country_name: "Bosnia and Herzegovina", country_code: "BA" },
    { country_name: "Botswana", country_code: "BW" },
    { country_name: "Brazil", country_code: "BR" },
    { country_name: "Brunei", country_code: "BN" },
    { country_name: "Bulgaria", country_code: "BG" },
    { country_name: "Burkina Faso", country_code: "BF" },
    { country_name: "Burundi", country_code: "BI" },
    { country_name: "Cabo Verde", country_code: "CV" },
    { country_name: "Cambodia", country_code: "KH" },
    { country_name: "Cameroon", country_code: "CM" },
    { country_name: "Canada", country_code: "CA" },
    { country_name: "Central African Republic", country_code: "CF" },
    { country_name: "Chad", country_code: "TD" },
    { country_name: "Chile", country_code: "CL" },
    { country_name: "China", country_code: "CN" },
    { country_name: "Colombia", country_code: "CO" },
    { country_name: "Comoros", country_code: "KM" },
    { country_name: "Congo (Congo-Brazzaville)", country_code: "CG" },
    { country_name: "Congo (Congo-Kinshasa)", country_code: "CD" },
    { country_name: "Costa Rica", country_code: "CR" },
    { country_name: "Croatia", country_code: "HR" },
    { country_name: "Cuba", country_code: "CU" },
    { country_name: "Cyprus", country_code: "CY" },
    { country_name: "Czechia", country_code: "CZ" },
    { country_name: "Denmark", country_code: "DK" },
    { country_name: "Djibouti", country_code: "DJ" },
    { country_name: "Dominica", country_code: "DM" },
    { country_name: "Dominican Republic", country_code: "DO" },
    { country_name: "Ecuador", country_code: "EC" },
    { country_name: "Egypt", country_code: "EG" },
    { country_name: "El Salvador", country_code: "SV" },
    { country_name: "Equatorial Guinea", country_code: "GQ" },
    { country_name: "Eritrea", country_code: "ER" },
    { country_name: "Estonia", country_code: "EE" },
    { country_name: "Eswatini", country_code: "SZ" },
    { country_name: "Ethiopia", country_code: "ET" },
    { country_name: "Fiji", country_code: "FJ" },
    { country_name: "Finland", country_code: "FI" },
    { country_name: "France", country_code: "FR" },
    { country_name: "Gabon", country_code: "GA" },
    { country_name: "Gambia", country_code: "GM" },
    { country_name: "Georgia", country_code: "GE" },
    { country_name: "Germany", country_code: "DE" },
    { country_name: "Ghana", country_code: "GH" },
    { country_name: "Greece", country_code: "GR" },
    { country_name: "Grenada", country_code: "GD" },
    { country_name: "Guatemala", country_code: "GT" },
    { country_name: "Guinea", country_code: "GN" },
    { country_name: "Guinea-Bissau", country_code: "GW" },
    { country_name: "Guyana", country_code: "GY" },
    { country_name: "Haiti", country_code: "HT" },
    { country_name: "Honduras", country_code: "HN" },
    { country_name: "Hungary", country_code: "HU" },
    { country_name: "Iceland", country_code: "IS" },
    { country_name: "India", country_code: "IN" },
    { country_name: "Indonesia", country_code: "ID" },
    { country_name: "Iran", country_code: "IR" },
    { country_name: "Iraq", country_code: "IQ" },
    { country_name: "Ireland", country_code: "IE" },
    { country_name: "Israel", country_code: "IL" },
    { country_name: "Italy", country_code: "IT" },
    { country_name: "Jamaica", country_code: "JM" },
    { country_name: "Japan", country_code: "JP" },
    { country_name: "Jordan", country_code: "JO" },
    { country_name: "Kazakhstan", country_code: "KZ" },
    { country_name: "Kenya", country_code: "KE" },
    { country_name: "South Korea", country_code: "KR" },
    { country_name: "United States", country_code: "US" },
    { country_name: "United Kingdom", country_code: "GB" },
    { country_name: "United Arab Emirates", country_code: "AE" },
    { country_name: "Zimbabwe", country_code: "ZW" },
];


export function getCountryCode(countryName: string): string | null {
    const country = countries.find(
        (c) => c.country_name.toLowerCase() === countryName.toLowerCase()
    );
    return country ? country.country_code : null;
}